#pragma once
#ifndef COMPILER_LAB_SYMBOL_H
#define COMPILER_LAB_SYMBOL_H

enum Symbol {
    DUMMY_STATEMENT,
    DUMMY_EXPRESSION,
    DUMMY_DECLARATOR,
    DUMMY,
    KEYWORD,
    LITERAL,
    TODO
};

#endif //COMPILER_LAB_SYMBOL_H